pipeline:
  run-koa-react-starter-tests:
    image: node:8.9
    commands:
      - ./bin/run.sh
    when:
      status: [ failure, success ]
      event: [ pull_request ]

services:
  mongo:
    image: mongo:3.4
branches: [ master, "*:master" ]
