version: '3.3'  
services:
  redis:
    image: redis:4.0.8
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - "6379:6379" # map port to none standard port, to avoid conflicts with locally installed redis.
  web:
    build:
      context: "./"
      dockerfile: Dockerfile.dev
    volumes:
      - "./src:/app/src"
    depends_on:
      - redis
    links:
      - redis
    environment:
      NODE_ENV: development
    ports:
      - "3002:3002"
      - "8081:8081"
